class TeamStylesheetService
  STYLESHEETS_DIR = Rails.root.join("app", "assets", "stylesheets", "teams")
  INDEX_FILE = Rails.root.join("app", "assets", "stylesheets", "teams.scss")

  def initialize(team)
    @team = team
  end

  def generate
    ensure_directory_exists
    write_stylesheet
    self.class.regenerate_index
  end

  def self.generate_for(team)
    new(team).generate
  end

  def self.generate_all
    ensure_directory_exists
    Team.includes(:colors, :styles).find_each do |team|
      new(team).generate
    end
    regenerate_index
  end

  def self.regenerate_index
    ensure_directory_exists
    partials = Dir.glob(STYLESHEETS_DIR.join("_*.scss")).sort

    content = []
    content << "// Team Stylesheets - Auto-generated index"
    content << "// Do not edit directly - regenerated by TeamStylesheetService"
    content << "// Last generated: #{Time.current.iso8601}"
    content << ""

    partials.each do |partial|
      filename = File.basename(partial, ".scss").sub(/^_/, "")
      content << "@import 'teams/#{filename}';"
    end

    File.write(INDEX_FILE, content.join("\n") + "\n")
  end

  def self.ensure_directory_exists
    FileUtils.mkdir_p(STYLESHEETS_DIR)
  end

  private

  def ensure_directory_exists
    self.class.ensure_directory_exists
  end

  def write_stylesheet
    File.write(stylesheet_path, stylesheet_content)
  end

  def stylesheet_path
    STYLESHEETS_DIR.join("_#{@team.scss_slug}.scss")
  end

  def stylesheet_content
    content = []
    content << file_header
    content << color_variables
    content << style_classes
    content << default_style_alias
    content.flatten.compact.join("\n")
  end

  def file_header
    [
      "// Team: #{@team.display_name}",
      "// Generated: #{Time.current.iso8601}",
      "// Do not edit directly - regenerate via TeamStylesheetService",
      ""
    ]
  end

  def color_variables
    return [] if @team.colors.empty?

    lines = [ "// Color Variables" ]
    @team.colors.ordered.each do |color|
      variable_name = color_variable_name(color)
      lines << "$#{variable_name}: ##{color.hex};"
    end
    lines << ""
    lines
  end

  def color_variable_name(color)
    color_slug = color.name.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/-+$/, "")
    "#{@team.scss_prefix}-#{color_slug}"
  end

  def style_classes
    return [] if @team.styles.empty?

    lines = [ "// Style Classes" ]
    @team.styles.ordered.each do |style|
      class_name = style_class_name(style)
      lines << ".#{class_name} {"
      lines << "  #{add_important_to_css(style.css)}"
      lines << "}"
      lines << ""
    end
    lines
  end

  # Add !important to background-color and color properties to override Falcon theme table styles
  def add_important_to_css(css)
    css.gsub(/\b(background-color|color):\s*([^;]+);/) do |match|
      prop, value = $1, $2.strip
      if value.end_with?("!important")
        match
      else
        "#{prop}: #{value} !important;"
      end
    end
  end

  def style_class_name(style)
    style_slug = style.name.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/-+$/, "")
    "#{@team.scss_prefix}-#{style_slug}"
  end

  def default_style_alias
    default_style = @team.styles.find_by(default: true)
    return [] unless default_style

    default_class = "#{@team.scss_prefix}-default"
    source_class = style_class_name(default_style)

    [
      "// Default Style Alias",
      ".#{default_class} {",
      "  @extend .#{source_class};",
      "}",
      ""
    ]
  end
end
