# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# Seed Leagues
League.destroy_all
Conference.destroy_all
Division.destroy_all
Affiliation.destroy_all

# NFL Structure
# League
nfl = League.create({ sport: "football", level: "pro", gender: "m", abbr: "NFL", name: "National Football League", periods: 4 })
# Divisions
nfc = Conference.create({ league: nfl, abbr: "NFC", name: "National Football Conference" })
afc = Conference.create({ league: nfl, abbr: "AFC", name: "American Football Conference" })
# Conferences
nfcw = Division.create({ conference: nfc, abbr: "W", name: "West", order: 1 })
nfcn = Division.create({ conference: nfc, abbr: "N", name: "North", order: 2 })
nfcs = Division.create({ conference: nfc, abbr: "S", name: "South", order: 3 })
nfce = Division.create({ conference: nfc, abbr: "E", name: "East", order: 4 })
afcw = Division.create({ conference: afc, abbr: "W", name: "West", order: 1 })
afcn = Division.create({ conference: afc, abbr: "N", name: "North", order: 2 })
afcs = Division.create({ conference: afc, abbr: "S", name: "South", order: 3 })
afce = Division.create({ conference: afc, abbr: "E", name: "East", order: 4 })

# NCAA Football Structure
ncaaf = League.create({ sport: "football", level: "college", ender: "m", abbr: "NCAAF", name: "NCAA FBS Football", periods: 4 })
# Conferences
acc  = Conference.create({ league: ncaaf, abbr: "ACC",   name: "Atlantic Coast Conference" })
aac  = Conference.create({ league: ncaaf, abbr: "AAC",   name: "American Athletic Conference" })
b12  = Conference.create({ league: ncaaf, abbr: "B12",   name: "Big 12 Conference" })
b1g  = Conference.create({ league: ncaaf, abbr: "B1G",   name: "Big Ten Conference" })
cusa = Conference.create({ league: ncaaf, abbr: "C-USA", name: "Conference USA" })
ind  = Conference.create({ league: ncaaf, abbr: "IND",   name: "FBS Independents" })
mac  = Conference.create({ league: ncaaf, abbr: "MAC",   name: "Mid-American Conference" })
mwc  = Conference.create({ league: ncaaf, abbr: "MWC",   name: "Mountain West Conference" })
pac  = Conference.create({ league: ncaaf, abbr: "PAC",   name: "Pac-12 Conference" })
sec  = Conference.create({ league: ncaaf, abbr: "SEC",   name: "Southeastern Conference" })
sun  = Conference.create({ league: ncaaf, abbr: "SUN",   name: "Sun Belt Conference" })
# Divisions (thank god the NCAA doesn't use divisions anymore so this is just a mirror of conferences)
Division.create({ conference: acc,  abbr: "ACC",   name: "Atlantic Coast Conference" })
Division.create({ conference: aac,  abbr: "AAC",   name: "American Athletic Conference" })
Division.create({ conference: b12,  abbr: "B12",   name: "Big 12 Conference" })
Division.create({ conference: b1g,  abbr: "B1G",   name: "Big Ten Conference" })
Division.create({ conference: cusa, abbr: "C-USA", name: "Conference USA"})
Division.create({ conference: ind,  abbr: "IND",   name: "FBS Independents" })
Division.create({ conference: mac,  abbr: "MAC",   name: "Mid-American Conference" })
Division.create({ conference: mwc,  abbr: "MWC",   name: "Mountain West Conference" })
Division.create({ conference: pac,  abbr: "PAC",   name: "Pac-12 Conference" })
Division.create({ conference: sec,  abbr: "SEC",   name: "Southeastern Conference" })
Division.create({ conference: sun,  abbr: "SUN",   name: "Sun Belt Conference" })

# NBA Structure
nba     = League.create({ sport: "basketball", level: "pro", gender: "m", abbr: "NBA", name: "National Basketball Association", periods: 4 })
# Conferences
nbae = Conference.create({ league: nba, abbr: "EAST", name: "Eastern Conference" })
nbaw = Conference.create({ league: nba, abbr: "WEST", name: "Western Conference" })
# Divisions
Division.create({ conference: nbae, abbr: "ATL", name: "Atlantic Division" })
Division.create({ conference: nbae, abbr: "CEN", name: "Central Division" })
Division.create({ conference: nbae, abbr: "SOE", name: "Southeastern Division" })
Division.create({ conference: nbaw, abbr: "NOW", name: "Northwest Division" })
Division.create({ conference: nbaw, abbr: "PAC", name: "Pacific Divsion" })
Division.create({ conference: nbaw, abbr: "SOW", name: "Southwest Division" })

# WNBA Structure
wnba    = League.create({ sport: "basketball", level: "pro", gender: "w", abbr: "WNBA", name: "Women's National Basketball Association", periods: 4 })
# Conferences
wnbae = Conference.create({ league: wnba, abbr: "EAST", name: "Eastern Conference" })
wnbaw = Conference.create({ league: wnba, abbr: "WEST", name: "Western Conference" })
# Divisions
Division.create({ conference: wnbae, abbr: "EAST", name: "Eastern Conference" })
Division.create({ conference: wnbaw, abbr: "WEST", name: "Western Conference" })

# NCAA Men's Basketball Structure
ncaambb = League.create({ sport: "basketball", evel: "college", gender: "m", abbr: "NCAAMBB", name: "NCAA Men's Basketball", periods: 2 })
# Conferences
acc   = Conference.create({ league: ncaambb, abbr: "ACC", name: "Atlantic Coast Conference" })
asun  = Conference.create({ league: ncaambb, abbr: "ASUN", name: "Atlantic Sun Conference" })
aeast = Conference.create({ league: ncaambb, abbr: "A-EAST", name: "America East Conference" })
aac   = Conference.create({ league: ncaambb, abbr: "AAC", name: "American Athletic Conference" })
a10   = Conference.create({ league: ncaambb, abbr: "A10", name: "Atlantic 10 Conference" })
b12   = Conference.create({ league: ncaambb, abbr: "B12", name: "Big 12 Conference" })
east  = Conference.create({ league: ncaambb, abbr: "EAST", name: "Big East Conference" })
sky   = Conference.create({ league: ncaambb, abbr: "SKY", name: "Big Sky Conference" })
bigs  = Conference.create({ league: ncaambb, abbr: "BIGS", name: "Big South Conference "})
b1g   = Conference.create({ league: ncaambb, abbr: "B1G", name: "Big Ten Conference" })
west  = Conference.create({ league: ncaambb, abbr: "WEST", name: "Big West Conference "})
cc    = Conference.create({ league: ncaambb, abbr: "CC", name: "Coastal Conference" })
cusa  = Conference.create({ league: ncaambb, abbr: "C-USA", name: "Conference USA" })
hor   = Conference.create({ league: ncaambb, abbr: "HOR", name: "Horizon League" })
ind   = Conference.create({ league: ncaambb, abbr: "IND", name: "Independents" })
ivy   = Conference.create({ league: ncaambb, abbr: "IVY", name: "Ivy League" })
meac  = Conference.create({ league: ncaambb, abbr: "MEAC", name: "Mid-East Athletic Conference" })
maac  = Conference.create({ league: ncaambb, abbr: "MAAC", name: "Metro Atlantic Athletic Conference" })
mac   = Conference.create({ league: ncaambb, abbr: "MAC", name: "Mid-American Conference" })
mvc   = Conference.create({ league: ncaambb, abbr: "MVC", name: "Missouri Valley Conference" })
mwc   = Conference.create({ league: ncaambb, abbr: "MWC", name: "Mountain West Conference" })
nec   = Conference.create({ league: ncaambb, abbr: "NEC", name: "Northeast Conference" })
ovc   = Conference.create({ league: ncaambb, abbr: "OVC", name: "Ohio Valley Conference" })
pac   = Conference.create({ league: ncaambb, abbr: "PAC", name: "Pac-12 Conference" })
pat   = Conference.create({ league: ncaambb, abbr: "PAT", name: "Patriot League" })
sec   = Conference.create({ league: ncaambb, abbr: "SEC", name: "Southeast Conference" })
swac  = Conference.create({ league: ncaambb, abbr: "SWAC", name: "Southwest Athletic Conference" })
sou   = Conference.create({ league: ncaambb, abbr: "SOU", name: "Southern Conference" })
slc   = Conference.create({ league: ncaambb, abbr: "SLC", name: "Southland Conference" })
smit  = Conference.create({ league: ncaambb, abbr: "SMIT", name: "Summit League" })
sun   = Conference.create({ league: ncaambb, abbr: "SUN", name: "Sun Belt Conference" })
wac   = Conference.create({ league: ncaambb, abbr: "WAC", name: "Western Athletic Conference" })
wcc   = Conference.create({ league: ncaambb, abbr: "WCC", name: "West Coast Conference" })
# Divisions
Division.create({ conference: acc, abbr: "ACC", name: "Atlantic Coast Conference" })
Division.create({ conference: asun, abbr: "ASUN", name: "Atlantic Sun Conference" })
Division.create({ conference: aeast, abbr: "A-EAST", name: "America East Conference" })
Division.create({ conference: aac, abbr: "AAC", name: "American Athletic Conference" })
Division.create({ conference: a10, abbr: "A10", name: "Atlantic 10 Conference" })
Division.create({ conference: b12, abbr: "B12", name: "Big 12 Conference" })
Division.create({ conference: east, abbr: "EAST", name: "Big East Conference" })
Division.create({ conference: sky, abbr: "SKY", name: "Big Sky Conference" })
Division.create({ conference: bigs, abbr: "BIGS", name: "Big South Conference "})
Division.create({ conference: b1g, abbr: "B1G", name: "Big Ten Conference" })
Division.create({ conference: west, abbr: "WEST", name: "Big West Conference "})
Division.create({ conference: cc, abbr: "CC", name: "Coastal Conference" })
Division.create({ conference: cusa, abbr: "C-USA", name: "Conference USA" })
Division.create({ conference: hor, abbr: "HOR", name: "Horizon League" })
Division.create({ conference: ind, abbr: "IND", name: "Independents" })
Division.create({ conference: ivy, abbr: "IVY", name: "Ivy League" })
Division.create({ conference: meac, abbr: "MEAC", name: "Mid-East Athletic Conference" })
Division.create({ conference: maac, abbr: "MAAC", name: "Metro Atlantic Athletic Conference" })
Division.create({ conference: mac, abbr: "MAC", name: "Mid-American Conference" })
Division.create({ conference: mvc, abbr: "MVC", name: "Missouri Valley Conference" })
Division.create({ conference: mwc, abbr: "MWC", name: "Mountain West Conference" })
Division.create({ conference: nec, abbr: "NEC", name: "Northeast Conference" })
Division.create({ conference: ovc, abbr: "OVC", name: "Ohio Valley Conference" })
Division.create({ conference: pac, abbr: "PAC", name: "Pac-12 Conference" })
Division.create({ conference: pat, abbr: "PAT", name: "Patriot League" })
Division.create({ conference: sec, abbr: "SEC", name: "Southeast Conference" })
Division.create({ conference: swac, abbr: "SWAC", name: "Southwest Athletic Conference" })
Division.create({ conference: sou, abbr: "SOU", name: "Southern Conference" })
Division.create({ conference: slc, abbr: "SLC", name: "Southland Conference" })
Division.create({ conference: smit, abbr: "SMIT", name: "Summit League" })
Division.create({ conference: sun, abbr: "SUN", name: "Sun Belt Conference" })
Division.create({ conference: wac, abbr: "WAC", name: "Western Athletic Conference" })
Division.create({ conference: wcc, abbr: "WCC", name: "West Coast Conference" })

# NCAA Women's Basketball Structure
ncaawbb = league.create({ sport: "basketball", level: "pro", gender: "w", abbr: "NCAAWBB", name: "NCAA Women's Basketball", periods: 4 })
# Conferences
acc   = Conference.create({ league: ncaawbb, abbr: "ACC", name: "Atlantic Coast Conference" })
asun  = Conference.create({ league: ncaawbb, abbr: "ASUN", name: "Atlantic Sun Conference" })
aeast = Conference.create({ league: ncaawbb, abbr: "A-EAST", name: "America East Conference" })
aac   = Conference.create({ league: ncaawbb, abbr: "AAC", name: "American Athletic Conference" })
a10   = Conference.create({ league: ncaawbb, abbr: "A10", name: "Atlantic 10 Conference" })
b12   = Conference.create({ league: ncaawbb, abbr: "B12", name: "Big 12 Conference" })
east  = Conference.create({ league: ncaawbb, abbr: "EAST", name: "Big East Conference" })
sky   = Conference.create({ league: ncaawbb, abbr: "SKY", name: "Big Sky Conference" })
bigs  = Conference.create({ league: ncaawbb, abbr: "BIGS", name: "Big South Conference "})
b1g   = Conference.create({ league: ncaawbb, abbr: "B1G", name: "Big Ten Conference" })
west  = Conference.create({ league: ncaawbb, abbr: "WEST", name: "Big West Conference "})
cc    = Conference.create({ league: ncaawbb, abbr: "CC", name: "Coastal Conference" })
cusa  = Conference.create({ league: ncaawbb, abbr: "C-USA", name: "Conference USA" })
hor   = Conference.create({ league: ncaawbb, abbr: "HOR", name: "Horizon League" })
ind   = Conference.create({ league: ncaawbb, abbr: "IND", name: "Independents" })
ivy   = Conference.create({ league: ncaawbb, abbr: "IVY", name: "Ivy League" })
meac  = Conference.create({ league: ncaawbb, abbr: "MEAC", name: "Mid-East Athletic Conference" })
maac  = Conference.create({ league: ncaawbb, abbr: "MAAC", name: "Metro Atlantic Athletic Conference" })
mac   = Conference.create({ league: ncaawbb, abbr: "MAC", name: "Mid-American Conference" })
mvc   = Conference.create({ league: ncaawbb, abbr: "MVC", name: "Missouri Valley Conference" })
mwc   = Conference.create({ league: ncaawbb, abbr: "MWC", name: "Mountain West Conference" })
nec   = Conference.create({ league: ncaawbb, abbr: "NEC", name: "Northeast Conference" })
ovc   = Conference.create({ league: ncaawbb, abbr: "OVC", name: "Ohio Valley Conference" })
pac   = Conference.create({ league: ncaawbb, abbr: "PAC", name: "Pac-12 Conference" })
pat   = Conference.create({ league: ncaawbb, abbr: "PAT", name: "Patriot League" })
sec   = Conference.create({ league: ncaawbb, abbr: "SEC", name: "Southeast Conference" })
swac  = Conference.create({ league: ncaawbb, abbr: "SWAC", name: "Southwest Athletic Conference" })
sou   = Conference.create({ league: ncaawbb, abbr: "SOU", name: "Southern Conference" })
slc   = Conference.create({ league: ncaawbb, abbr: "SLC", name: "Southland Conference" })
smit  = Conference.create({ league: ncaawbb, abbr: "SMIT", name: "Summit League" })
sun   = Conference.create({ league: ncaawbb, abbr: "SUN", name: "Sun Belt Conference" })
wac   = Conference.create({ league: ncaawbb, abbr: "WAC", name: "Western Athletic Conference" })
wcc   = Conference.create({ league: ncaawbb, abbr: "WCC", name: "West Coast Conference" })
# Divisions
Division.create({ conference: acc, abbr: "ACC", name: "Atlantic Coast Conference" })
Division.create({ conference: asun, abbr: "ASUN", name: "Atlantic Sun Conference" })
Division.create({ conference: aeast, abbr: "A-EAST", name: "America East Conference" })
Division.create({ conference: aac, abbr: "AAC", name: "American Athletic Conference" })
Division.create({ conference: a10, abbr: "A10", name: "Atlantic 10 Conference" })
Division.create({ conference: b12, abbr: "B12", name: "Big 12 Conference" })
Division.create({ conference: east, abbr: "EAST", name: "Big East Conference" })
Division.create({ conference: sky, abbr: "SKY", name: "Big Sky Conference" })
Division.create({ conference: bigs, abbr: "BIGS", name: "Big South Conference "})
Division.create({ conference: b1g, abbr: "B1G", name: "Big Ten Conference" })
Division.create({ conference: west, abbr: "WEST", name: "Big West Conference "})
Division.create({ conference: cc, abbr: "CC", name: "Coastal Conference" })
Division.create({ conference: cusa, abbr: "C-USA", name: "Conference USA" })
Division.create({ conference: hor, abbr: "HOR", name: "Horizon League" })
Division.create({ conference: ind, abbr: "IND", name: "Independents" })
Division.create({ conference: ivy, abbr: "IVY", name: "Ivy League" })
Division.create({ conference: meac, abbr: "MEAC", name: "Mid-East Athletic Conference" })
Division.create({ conference: maac, abbr: "MAAC", name: "Metro Atlantic Athletic Conference" })
Division.create({ conference: mac, abbr: "MAC", name: "Mid-American Conference" })
Division.create({ conference: mvc, abbr: "MVC", name: "Missouri Valley Conference" })
Division.create({ conference: mwc, abbr: "MWC", name: "Mountain West Conference" })
Division.create({ conference: nec, abbr: "NEC", name: "Northeast Conference" })
Division.create({ conference: ovc, abbr: "OVC", name: "Ohio Valley Conference" })
Division.create({ conference: pac, abbr: "PAC", name: "Pac-12 Conference" })
Division.create({ conference: pat, abbr: "PAT", name: "Patriot League" })
Division.create({ conference: sec, abbr: "SEC", name: "Southeast Conference" })
Division.create({ conference: swac, abbr: "SWAC", name: "Southwest Athletic Conference" })
Division.create({ conference: sou, abbr: "SOU", name: "Southern Conference" })
Division.create({ conference: slc, abbr: "SLC", name: "Southland Conference" })
Division.create({ conference: smit, abbr: "SMIT", name: "Summit League" })
Division.create({ conference: sun, abbr: "SUN", name: "Sun Belt Conference" })
Division.create({ conference: wac, abbr: "WAC", name: "Western Athletic Conference" })
Division.create({ conference: wcc, abbr: "WCC", name: "West Coast Conference" })
